services:
  - type: web
    name: node-no-show-prediction
    env: node
    rootDir: node-backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free

  - type: web
    name: python-no-show-prediction
    env: python
    rootDir: python-backend
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free